components {
  id: "script"
  component: "/assets/go/scripts/car.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"cartest\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlas/go.atlas\"\n"
  "}\n"
  ""
  position {
    y: -51.0
    z: 1.5
  }
}
embedded_components {
  id: "collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 60.0\n"
  "friction: 0.0\n"
  "restitution: 1.0\n"
  "group: \"dynamic\"\n"
  "mask: \"static\"\n"
  "mask: \"dynamic\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -83.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"body\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 35.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"front\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -196.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"back\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -30.0\n"
  "      y: 22.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 9\n"
  "    count: 1\n"
  "    id: \"frontleft\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 30.0\n"
  "      y: 22.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 10\n"
  "    count: 1\n"
  "    id: \"frontright\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: -31.0\n"
  "      y: -180.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 11\n"
  "    count: 1\n"
  "    id: \"backright\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 30.0\n"
  "      y: -180.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 12\n"
  "    count: 1\n"
  "    id: \"backleft\"\n"
  "  }\n"
  "  data: 55.0\n"
  "  data: 105.0\n"
  "  data: 10.0\n"
  "  data: 28.5\n"
  "  data: 13.0\n"
  "  data: 10.0\n"
  "  data: 39.5\n"
  "  data: 8.5\n"
  "  data: 10.0\n"
  "  data: 24.0\n"
  "  data: 24.0\n"
  "  data: 24.0\n"
  "  data: 24.0\n"
  "}\n"
  "locked_rotation: true\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
