embedded_components {
  id: "shadow"
  type: "sprite"
  data: "default_animation: \"shadow\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 100.0\n"
  "  y: 100.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlas/go.atlas\"\n"
  "}\n"
  ""
}
