components {
  id: "mission"
  component: "/assets/go/scripts/mission.script"
}
components {
  id: "script"
  component: "/assets/go/scripts/player.script"
}
embedded_components {
  id: "collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.0\n"
  "restitution: 1.0\n"
  "group: \"dynamic\"\n"
  "mask: \"payphone\"\n"
  "mask: \"static\"\n"
  "mask: \"dynamic\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"head\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -20.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"left\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 20.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "    id: \"right\"\n"
  "  }\n"
  "  data: 15.5\n"
  "  data: 15.5\n"
  "  data: 10.0\n"
  "  data: 6.0\n"
  "  data: 5.5\n"
  "  data: 10.0\n"
  "  data: 6.0\n"
  "  data: 5.5\n"
  "  data: 10.0\n"
  "}\n"
  "locked_rotation: true\n"
  "event_collision: false\n"
  "event_contact: false\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"player_1\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 360.0\n"
  "  y: 360.0\n"
  "}\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlas/go.atlas\"\n"
  "}\n"
  ""
  position {
    z: 1.0
  }
  scale {
    x: 0.2
    y: 0.2
  }
}
